batch_size: 32
conv_layers:
- - 64
  - 128
dataset: mrd
dgm_layers:
- - 256
  - 128
  - 64
distance: euclidean
dropout: 0.3
encoder_name: distilbert-base-uncased
fc_layers:
- 512
- 256
- 128
- 64
- 32
- 1
ffun: mlp
freeze_encoder: false
gfun: gat
input_dim: 768
k: 5
lambda_connect: 0.001
lambda_entropy: 0.001
lambda_locality: 0.01
lambda_sparse: 0.01
lr: 0.001
max_epochs: 100
max_length: 512
model_type: baseline
num_workers: 4
patience: 10
pooling: mean
pre_fc:
- 768
- 256
remove_punctualization: false
resume_from_checkpoint: null
task: regression
test_eval: 10
use_continuous_dgm: false
val_split: 0.2
weight_decay: 0.01
